// <auto-generated />
using M7.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace M7.Migrations
{
    [DbContext(typeof(BtsContext))]
    partial class BtsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("M7.Models.Bts", b =>
                {
                    b.Property<int>("BtsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ratings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BtsId");

                    b.ToTable("Bts");

                    b.HasData(
                        new
                        {
                            BtsId = 1,
                            Name = "Jimin",
                            Ratings = "9.8"
                        },
                        new
                        {
                            BtsId = 2,
                            Name = "RM",
                            Ratings = "10"
                        },
                        new
                        {
                            BtsId = 3,
                            Name = "Suga",
                            Ratings = "9"
                        },
                        new
                        {
                            BtsId = 4,
                            Name = "Jungkook",
                            Ratings = "6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
